version: '4'
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "C:/Users/swast/OneDrive/Desktop/infer:/Inference"
    command: uvicorn main:app --host 0.0.0.0 --port 8000




  # streamlit:
  #   build:
  #     context: .
  #   ports:
  #     - "8000:8501" 
  #   command: streamlit run ui.py --server.port 8501
